quarkus.http.port=8083
stomp4j.client.url=${STOMP4J_CLIENT_URL:stomp://localhost:61613}
stomp4j.client.username=${STOMP4J_CLIENT_USERNAME:user}
stomp4j.client.password=${STOMP4J_CLIENT_PASSWORD:passwd}
