quarkus.http.port=8084
stomp4j.server.server-name=quarkus-server-sample
stomp4j.server.channels[0].type=TCP
stomp4j.server.channels[0].port=5520
stomp4j.server.channels[1].type=WEB_SOCKET
stomp4j.server.channels[1].port=5521
