bridge.kafka.bootstrap-servers=localhost:9092
bridge.kafka.consumer-group-id=stomp4j-bridge
bridge.destination.prefix=/topic/
bridge.topic.prefix-strip=/topic/
bridge.stomp.tcp-port=61613
bridge.stomp.ws-port=61614
